### ISSUE TITLE
Handling of Exceptions in Scopes

### ISSUE THREAD

**Issue by maxfischer2781** [MaineKuehn/usim#26]
It seems that ``Scope`` does not properly catch-reraise exceptions in children. It still misses the facilities to detect errors in children and abort itself.

**Comment by eileen-kuehn** [comment]
I would propose to write some unit tests showing this behaviour, or did you already do?

**Comment by maxfischer2781** [comment]
No, I haven't done so yet. Good idea.

**Comment by maxfischer2781** [comment]
Fixed with #27. See also follow up improvements #29 and #30.
