### ISSUE TITLE
Scopes swallow exceptions during shutdown

### ISSUE THREAD

**Issue by maxfischer2781** [MaineKuehn/usim#83]
**Description of the bug**
If an activity receives an exception *during* scope shutdown (``__aexit__``) it is suppressed. The cause is that ``Scope.__aexit__ -> False`` is assumed to re-raise the *current* exception, but it only re-raises the exception with which the scope was entered.

**How To Reproduce**
In the following example, ``suppressing`` should be killed by a CancelTask. The ``usim.instant`` causes this to be received *during* Scope shutdown.

```
async def suppressing():
    async with usim.Scope() as scope:
        ...

async def setup():
    async with usim.Scope() as scope:
        task = scope.do(suppressing())
        await usim.instant  # advance suppressing Scope to shutdown
        task.cancel()
    await task

usim.run(setup())
```

**Expected behaviour**
The ``Scope`` should raise the most recent exception.

**Comment by eileen-kuehn** [comment]
I cannot reproduce the error with the given code (I tried to make a unit test out of it).
