### ISSUE TITLE
Checking for compatibility with SimPy 4

### ISSUE THREAD

**Issue by eileen-kuehn** [MaineKuehn/usim#97]
SimPy came up with version 4 around 2 months ago. There were some changes, most importantly they now only work with Python 3.6+. Further, the following changes are mentioned in the documentation:

* ``BaseEnvironment`` has been dropped, ``Environment`` should be used instead
* Returning from Process generators now by ``return`` keyword: usage of ``Environment.exit(value)`` and ``raise StopProcess(value)`` should be replaced by ``return``

Source: https://simpy.readthedocs.io/en/latest/topical_guides/porting_from_simpy3.html

We should double check if everything works as expected.

**Comment by maxfischer2781** [comment]
We never added ``BaseEnvironment``. It is not listed as unsupported in the docs either.

We do have ``Environment.exit`` and ``StopProcess``. Both are listed in the docs as well. We natively support ``return`` already.
